on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

name: Mobile Build
jobs:
  build:
    name: Build and test APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '9.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get Flutter packages
        run: |
          flutter pub get
      - name: Run Flutter tests
        run: |
          flutter test
      - name: Build APK
        run: |
          flutter build apk --debug
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: mobile/build/app/outputs/apk/debug/app-*.apk
      - name: Check dependencies
        run: |
          flutter pub run dependency_validator --ignore coverage,dartdoc,cupertino_icons,flutter_launcher_icons,flutter_launcher_name
